#sdk: "/Users/gporemba/.rvm/gems/ruby-1.9.3-p194/gems/rhodes-4.0.0"
sdkversion: "4.0.0"
name: "Rhospection2"
version: 1.0
vendor: "rhomobile"
build: "debug"
bbver: 6.0
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator6.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.rhospection2"
  BundleURLScheme: "rhospection2"
wp:
  productid: "deaa1cc0-0cce-0131-2ced-482a14102b63"
symbian:
  uid: "0xe963c942"
android:
  version: "2.3.3"
extensions:
  - rhoconnect-client
